name: Test

on:
  pull_request:
    paths-ignore: ['**.md', 'docs/**', 'LICENSE']
  push:
    paths-ignore: ['**.md', 'docs/**', 'LICENSE']
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  dispatch:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install

      - run: npm test
